#!/bin/bash
set -e

echo "=== WaterPrize (Python) — подготовка к деплою на bothost.ru ==="

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$BASE_DIR"

# Проверка secrets — чтобы не залить токен в репозиторий
if git rev-parse --git-dir > /dev/null 2>&1; then
    if git ls-files .env --error-unmatch 2>/dev/null; then
        echo "[!] ОПАСНОСТЬ: .env отслеживается git! Добавьте его в .gitignore"
        exit 1
    fi
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  ДЕПЛОЙ НА BOTHOST.RU (Python + Dockerfile)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  1. Запушьте код в GitHub/GitLab репозиторий:"
echo "     git add ."
echo "     git commit -m \"initial\""
echo "     git push"
echo ""
echo "  2. Зайдите на https://bothost.ru → Создать бота"
echo ""
echo "  3. Заполните форму:"
echo "     - Название: WaterPrize"
echo "     - Платформа: Telegram"
echo "     - Библиотека: Python (любая — bothost увидит Dockerfile)"
echo "     - Bot Token: токен из @BotFather"
echo "     - Git URL: https://github.com/ваш-username/waterprize"
echo "     - Ветка: main"
echo "     - Порт: 8080"
echo ""
echo "  4. В настройках → Переменные окружения (все обязательны):"
echo "     ┌──────────────────────┬─────────────────────────────┐"
echo "     │ BOT_TOKEN            │ токен из @BotFather         │"
echo "     │ ADMIN_IDS            │ 818439646                   │"
echo "     │ DB_HOST              │ хост PostgreSQL             │"
echo "     │ DB_PORT              │ 5432                        │"
echo "     │ DB_NAME              │ waterprize                  │"
echo "     │ DB_USER              │ пользователь БД             │"
echo "     │ DB_PASS              │ пароль БД                   │"
echo "     │ BOT_USERNAME         │ waterMoscowBot              │"
echo "     └──────────────────────┴─────────────────────────────┘"
echo ""
echo "  5. Включите «Использовать домен»"
echo ""
echo "  6. Нажмите «Перезапустить» — бот соберётся по Dockerfile"
echo ""
echo "  7. После запуска установите вебхук Telegram:"
echo "     https://api.telegram.org/bot<ТОКЕН>/setWebhook"
echo "       ?url=https://ваш-домен.bothost.tech/webhook"
echo ""
echo "  8. Проверка статуса:"
echo "     https://api.telegram.org/bot<ТОКЕН>/getWebhookInfo"
echo ""
echo "  Для локального запуска (нужен Python 3.12, PostgreSQL):"
echo "     pip install -r requirements.txt"
echo "     cp .env.example .env  # настроить параметры"
echo "     python -m uvicorn app.main:app --reload --port 8080"
echo ""
echo "  Для настройки вебхука локально (через Cloudflare Tunnel):"
echo "     python -m app.config_webhook set https://туннель.bothost.tech/webhook"
echo ""
echo "═══════════════════════════════════════════════════════════════"